### ISSUE TITLE
No Music files found

### ISSUE THREAD

**Issue by htl-leonding** [htl-leonding/2015_fiply#28]
Even having mp3's on the device, the app cannot find the files

**Comment by DenkerMayr** [comment]
At Startup all the Musicfiles are now read from the Mediastore instead of the Music-Folder.
This means the searching of Files is handled by the OS and not by our App.

**Comment by htl-leonding** [comment]
New error, when showing dialog for permitting access
```
02-17 18:11:27.387 4803-4803/htl_leonding.fiplyteam.fiply E/WindowManager: android.view.WindowLeaked: Activity htl_leonding.fiplyteam.fiply.menu.SplashActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{2e77ddb V.E...... R....... 0,0-1026,358} that was originally added here
                                                                               at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
                                                                               at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
                                                                               at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                               at android.app.Dialog.show(Dialog.java:319)
                                                                               at htl_leonding.fiplyteam.fiply.music.ReadMusic.showMessageOKCancel(ReadMusic.java:87)
                                                                               at htl_leonding.fiplyteam.fiply.music.ReadMusic.access$000(ReadMusic.java:24)
                                                                               at htl_leonding.fiplyteam.fiply.music.ReadMusic$1.run(ReadMusic.java:65)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


```

**Comment by DenkerMayr** [comment]
Issue should be resolved with our latest few commits.
